const IMG = (name) => `/products/poshact/${name}`;

export const POSHACT_MODULES = [
  {
    id: "dashboard",
    category: "universal",
    categoryLabel: "Universal",
    icon: "gauge",
    name: "Dashboard",
    url: "posh.app/dashboard",
    section: "Main screen",
    title: "Dashboard for every role",
    desc: "Each role sees a home screen that fits their work — IC members see open cases and deadline alerts, admins see Section 19 duty progress, employees see policy status and quick links.",
    bullets: [
      "Overdue inquiry alerts (90-day limit)",
      "Section 19 employer duty progress",
      "Open cases & pending management actions",
      "Policy confirmation status at a glance",
    ],
    image: IMG("dashboard.png"),
  },
  {
    id: "guide",
    category: "universal",
    categoryLabel: "Universal",
    icon: "book-open",
    name: "User Guide",
    url: "posh.app/guide",
    section: "Built-in documentation",
    title: "Role-based user guide & go-live checklist",
    desc: "In-app help with searchable articles, a simple law terms guide, and a 7-step admin checklist — so IC members and HR staff do not need to hunt for PDFs.",
    bullets: [
      "Articles by role (Employee, IC, Admin)",
      "Law terms guide & deadline reference",
      "Go-live checklist with progress tracking",
      "Quick-topic menu on the side",
    ],
    image: IMG("user-guide.png"),
  },
  {
    id: "employee-portal",
    category: "universal",
    categoryLabel: "Universal",
    icon: "user-shield",
    name: "Employee Portal",
    url: "posh.app/employee",
    section: "Employee experience",
    title: "Employee self-service portal",
    desc: "Employees read and confirm the POSH policy, view IC contacts, file complaints, and track their own cases — with privacy messages throughout.",
    bullets: [
      "Policy read & confirm with date/time saved",
      "IC contact list & helpline display",
      "Quick links to file complaint & my cases",
      "WhatsApp helpline & awareness resources",
    ],
    image: IMG("employee-portal.png"),
  },
  {
    id: "new-complaint",
    category: "universal",
    categoryLabel: "Universal",
    icon: "file-plus",
    name: "New Complaint",
    url: "posh.app/complaints/file",
    section: "Section 9 — Complaint Filing",
    title: "Private complaint form",
    desc: "Secure filing with anonymous option, file upload, details about the person complained against, and instant case number. Works for logged-in employees and public QR links.",
    bullets: [
      "Anonymous & named complaint options",
      "File attachments — IC-only access",
      "3 + 3 month filing window guidance",
      "Routes to Local Committee when employer is respondent",
    ],
    image: IMG("complaint-intake.png"),
  },
  {
    id: "my-cases",
    category: "universal",
    categoryLabel: "Universal",
    icon: "folder",
    name: "My Cases",
    url: "posh.app/complaints/my",
    section: "Employee tracking",
    title: "My cases status tracker",
    desc: "Complainants follow their case through every stage — from filing to closure — without showing private IC work or other party details.",
    bullets: [
      "Case number & current status display",
      "Timeline of visible stage updates",
      "Privacy notices at each step",
      "Link back to employee portal",
    ],
    image: IMG("my-cases.png"),
  },
  {
    id: "management",
    category: "universal",
    categoryLabel: "Universal",
    icon: "briefcase",
    name: "Management Portal",
    url: "posh.app/management",
    section: "Employer action",
    title: "Management action portal",
    desc: "Employer action after IC recommendations — warnings, transfers, termination — with 60-day legal deadline tracking.",
    bullets: [
      "Post-recommendation action queue",
      "60-day SLA visibility & alerts",
      "Implementation documentation records",
      "Links to IC Operate recommendation step",
    ],
    image: IMG("management-portal.png"),
  },
  {
    id: "all-cases",
    category: "ic-hr",
    categoryLabel: "IC / HR",
    icon: "folder-open",
    name: "All Cases",
    url: "posh.app/cases",
    section: "IC case list",
    title: "All cases — search, filter & status",
    desc: "IC members and HR see every complaint in one list with 15 status steps, filters, and quick access to work on a case or download evidence.",
    bullets: [
      "Search & filter by status, date, type",
      "15 case status steps",
      "Evidence download (IC-only access)",
      "One-click open in IC Operate wizard",
    ],
    image: IMG("all-cases.png"),
  },
  {
    id: "operate",
    category: "ic-hr",
    categoryLabel: "IC / HR",
    icon: "list-checks",
    name: "IC Operate",
    url: "posh.app/cases/operate",
    section: "Sections 9–12 — Inquiry",
    title: "9-step IC Operate wizard",
    desc: "Step-by-step guide from IC review through agreement, temporary relief, notice to respondent, inquiry, hearing, recommendation, management action, and closure.",
    bullets: [
      "Steps 1–9: Review → Agreement → Relief → Notice → Inquiry → Hearing → Recommend → Management → Close",
      "Deadline tracking at every stage",
      "Printable notices to respondent",
      "Law references shown per step",
    ],
    image: IMG("ic-operate.png"),
  },
  {
    id: "compliance",
    category: "ic-hr",
    categoryLabel: "IC / HR",
    icon: "clipboard-check",
    name: "Compliance",
    url: "posh.app/compliance",
    section: "Section 19 — Employer Duties",
    title: "Compliance command center",
    desc: "Track all 14 employer duties under Section 19 with completion percentage on the dashboard. Log workshops, IC training, and poster displays for inspection records.",
    bullets: [
      "14-item Section 19 checklist with status",
      "Prevention event log (workshops, posters)",
      "Dashboard completion % summary",
      "Date/time saved for inspection records",
    ],
    image: IMG("compliance.png"),
  },
  {
    id: "annual-report",
    category: "ic-hr",
    categoryLabel: "IC / HR",
    icon: "file-text",
    name: "Annual Report",
    url: "posh.app/reports/annual",
    section: "Section 22 — Annual Report",
    title: "One-click annual reporting",
    desc: "Create District Officer reports with summary case numbers, prevention events, employer duty status, and policy confirmations — no complainant names shown.",
    bullets: [
      "Year-wise report generation",
      "Print / export ready format",
      "Mark submitted tracking",
      "Summary stats only — Section 16 safe",
    ],
    image: IMG("annual-report.png"),
  },
  {
    id: "audit",
    category: "ic-hr",
    categoryLabel: "IC / HR",
    icon: "history",
    name: "Audit Log",
    url: "posh.app/audit-log",
    section: "Activity log",
    title: "Full activity log",
    desc: "Every important action — case updates, evidence access, policy changes, IC member edits — saved with user, date/time, and details for inspections.",
    bullets: [
      "Full searchable audit log",
      "Evidence access tracking",
      "Policy & IC change history",
      "Export-ready for inspections",
    ],
    image: IMG("audit-log.png"),
  },
  {
    id: "employees",
    category: "admin",
    categoryLabel: "Administration",
    icon: "users",
    name: "Employees",
    url: "posh.app/employees",
    section: "Directory",
    title: "Employee directory",
    desc: "Manage your employee list — add and edit employees in standalone mode, or sync from Payroll in HRMS mode with one-click login setup.",
    bullets: [
      "Standalone: add & edit employees",
      "HRMS: Payroll sync & read-only view",
      "Turn on POSH login per employee",
      "Department & designation fields",
    ],
    image: IMG("employees.png"),
  },
  {
    id: "ic-setup",
    category: "admin",
    categoryLabel: "Administration",
    icon: "users-round",
    name: "IC Setup",
    url: "posh.app/ic-setup",
    section: "Section 4 — IC Setup",
    title: "IC Setup",
    desc: "Set up your Internal Committee with Presiding Officer, internal and external members, and Member Secretary — with live check of the 50% women quota.",
    bullets: [
      "Presiding Officer & member roles",
      "External member support & badges",
      "Women quota indicator (50% rule)",
      "Pick from Payroll list (HRMS mode)",
    ],
    image: IMG("ic-setup-2.png"),
  },
  {
    id: "policy",
    category: "admin",
    categoryLabel: "Administration",
    icon: "file-signature",
    name: "Policy",
    url: "posh.app/policies",
    section: "Workplace policy",
    title: "Policy management & publish",
    desc: "Write, update, and publish your workplace POSH policy. Employees confirm through the portal — dates saved for annual reports and compliance records.",
    bullets: [
      "Draft & publish workflow",
      "Version history & activation",
      "Employee policy confirmation tracking",
      "Preview as employees see it",
    ],
    image: IMG("policy.png"),
  },
  {
    id: "settings",
    category: "admin",
    categoryLabel: "Administration",
    icon: "settings",
    name: "Settings",
    url: "posh.app/settings",
    section: "Organisation",
    title: "Settings",
    desc: "Set organisation profile, setup mode (HRMS or standalone), product name, and QR intake URL — all from one admin screen.",
    bullets: [
      "Org profile & branding",
      "HRMS ↔ Standalone setup toggle",
      "Change product name shown to users",
      "QR intake URL create & refresh",
    ],
    image: IMG("settings.png"),
  },
  {
    id: "qr-intake",
    category: "public",
    categoryLabel: "Public",
    icon: "qr-code",
    name: "QR Intake",
    url: "posh.app/intake/{orgKey}",
    section: "Public channel",
    title: "QR poster public intake",
    desc: "Meet notice-board display rules with a shareable URL and QR code. Anyone can file without login — complaints go to the same IC queue as internal ones.",
    bullets: [
      "Public form — no login needed",
      "Create a new secure org link when needed",
      "Anonymous option available",
      "Same IC workflow as internal complaints",
    ],
    image: IMG("qr-intake-3.png"),
  },
];

export const POSHACT_HERO_SLIDES = [
  { label: "Dashboard", sub: "Main screen", url: "posh.app/dashboard", image: IMG("dashboard.png") },
  { label: "IC Setup", sub: "Section 4 — IC Setup", url: "posh.app/ic-setup", image: IMG("ic-setup-2.png") },
  { label: "New Complaint", sub: "Section 9 — Private intake", url: "posh.app/complaints/file", image: IMG("complaint-intake.png") },
  { label: "IC Operate", sub: "9-Step Inquiry Wizard", url: "posh.app/cases/operate", image: IMG("ic-operate.png") },
  { label: "Compliance", sub: "Section 19 — Employer Duties", url: "posh.app/compliance", image: IMG("compliance.png") },
  { label: "Annual Report", sub: "Section 22 — District Officer", url: "posh.app/reports/annual", image: IMG("annual-report.png") },
  { label: "Employee Portal", sub: "Policy & employee self-help", url: "posh.app/employee", image: IMG("employee-portal.png") },
  { label: "Employer action", sub: "Management Portal", url: "posh.app/management", image: IMG("management-portal.png") },
];

export const POSHACT_CATEGORIES = [
  { id: "all", label: "All modules" },
  { id: "universal", label: "Universal" },
  { id: "ic-hr", label: "IC / HR" },
  { id: "admin", label: "Administration" },
  { id: "public", label: "Public" },
];

export const POSHACT_CATEGORY_INFO = {
  all: { title: "All modules", desc: "Every module in the product — pick one to preview the screen." },
  universal: { title: "Universal modules", desc: "Used by employees, IC members, HR, and management in day-to-day POSH work." },
  "ic-hr": { title: "IC / HR modules", desc: "Case handling, compliance tracking, reports, and audit tools for IC and HR teams." },
  admin: { title: "Administration modules", desc: "Setup and configuration — IC members, policy, employees, and org settings." },
  public: { title: "Public module", desc: "QR poster intake — file without login, same IC queue as internal complaints." },
};
